name: Publish Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'  # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: get version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'plugin.json'
          prop_path: 'Version'
      - run: echo ${{steps.version.outputs.prop}}
      - name: Build
        run: |
          dotnet publish 'Flow.Launcher.Plugin.AwsToolkit.csproj' --framework net5.0-windows -c Release -o "AWS Toolkit-${{steps.version.outputs.prop}}"
          7z a -tzip "Flow.Launcher.Plugin.AwsToolkit.zip" "AWS Toolkit-${{steps.version.outputs.prop}}"
          rm -r "AWS Toolkit-${{steps.version.outputs.prop}}"
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "Flow.Launcher.Plugin.AwsToolkit.zip"
          tag_name: "v${{steps.version.outputs.prop}}"
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
